[package]
name = "sightingdb"
version = "0.0.4"
authors = ["Sebastien Tricaud <sebastien.tricaud@devo.com>"]
edition = "2024"
rust-version = "1.85"
license = "BSD-3-Clause"
description = "A database designed for Sightings, a technique to count items"
repository = "https://github.com/stricaud/sightingdb"

[[bin]]
name = "sightingdb"
path = "src/main.rs"

[dependencies]
actix-web = { version = "4.14", features = ["openssl"] }
anyhow = "1.0"
chrono = { version = "0.4.45", features = ["serde"] }
clap = { version = "4.6", features = ["derive"] }
daemonize = "0.5"
dirs = "6.0"
log = "0.4"
log4rs = "1.4"
openssl = "0.10.81"
rust-ini = "0.21"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
actix-rt = "2.11"

[profile.release]
lto = "thin"
codegen-units = 1
